### ISSUE TITLE
Roadmap (Summer 2024 and beyond)

### ISSUE THREAD

**Issue by elsoroka** [elsoroka/Satisfiability.jl#46]
# Development Roadmap for Summer 2024 and beyond
## Minor features:
- [ ] #44 
- [ ] Chaining (`a < b < c`) #45 
- [x] #43 

## Expanding capabilities:
- [ ] #31. probably less difficult than #11.
- [ ] #11. This will probably involve work with metaprogramming to get right and need good unit testing.
- [ ] Completing the following three will take us to a **milestone:** all SMT-LIB theories supported. For each of these issues, a separate ticket should be created with a checklist for developing, testing, and documenting this feature.
    - [ ] Add SMT-LIB theory of floating point numbers https://smt-lib.org/theories.shtml
    - [ ] Add SMT-LIB theory of arrays https://smt-lib.org/theories.shtml
    - [ ] Add SMT-LIB theory of strings https://smt-lib.org/theories.shtml
- [ ]

## New features:
- [ ] #24. This should be straightforward to implement but requires understanding the logic types. Type promotion rules could be useful to encode the (https://smt-lib.org/logics.shtml)[hierarchy of logic types].

**Comment by Fe-r-oz** [comment]
Thank you very much for providing such a clear and detailed description of all these linked issues. It’s incredibly helpful. I’m excited to take on these tasks and contribute to the roadmap! I would like to start by taking a stab at Add SMT-LIB theory of `FloatingPoint`!
